language: node_js
node_js:
- node
services:
- mongodb
before_install: 
- cd backend
install:
- npm install
jobs:
  include:
  - stage: test
    script: npm test
  - stage: deploy
    install:
    - npm install
    - npm install -g serverless
    before_script: 
    - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
      -in .env.enc -out .env -d
    - openssl aes-256-cbc -K $encrypted_4e8c5512ae30_key -iv $encrypted_4e8c5512ae30_iv
      -in serverless-key.json.enc -out serverless-key.json -d
    script:
    - npm run deploy
