language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
before_install: 
- cd backend
install:
- npm install
jobs:
  include:
  - stage: test
    script: npm run test
  - stage: deploy
    before_script: 
    - openssl aes-256-cbc -K $encrypted_4e8c5512ae30_key -iv $encrypted_4e8c5512ae30_iv
      -in serverless-key.json.enc -out serverless-key.json -d
    script:
    - npm install -g serverless
    - npm run deploy
