service: cs3219-otot-task-b

provider:
  name: google
  stage: dev
  runtime: nodejs12
  project: cs3219-otot-task-b-325509
  credentials: ${env:TRAVIS_BUILD_DIR}/backend/serverless-key.json # <- the path must be absolute
  region: asia-southeast1
  environment: # Transfer the env variables from Travis to Google Cloud Functions
    MONGO_USERNAME: ${env:MONGO_USERNAME}
    MONGO_PASSWORD: ${env:MONGO_PASSWORD}
    MONGO_DB: ${env:MONGO_DB}

plugins:
  - serverless-plugin-typescript
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  app:
    handler: app
    runtime: nodejs12
    events:
      - http: path
